version: '3'

services:
  todotests:
    image: todotests
    restart: always
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - "todofront"
      - "todoback"
  todofront:
    image: todofrontend
    restart: always
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - "todoback"
  todoback:
    image: todobackend
    restart: always
